{
  "hash": "041b3f54ea825be15f044a7053c90fc2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB 520 - Final project\" \nsubtitle: \"Genomic prediction of yield in diverse spring wheat lines across multiple environment\" \nauthor: \"Yaotian Gao\" \ndate: \"2024-04-28\" \ncategories: [Genomic selection, yield prediction, spring wheat, multi-environment trials] \ndescription: \"\" \nformat: html \neditor: visual\nimage: \"1.png\"\ncode-fold: true\ntoc: true\n---\n\n\n# 1. Preamble\n\nWheat (*Triticum aestivum* L.), responsible for a significant portion of global caloric intake, is increasingly threatened by both natural and anthropogenic factors, including climate change and geopolitical unrest (Zhang et al. 2022). These challenges underline the urgency for innovative approaches in wheat breeding, beyond the capabilities of traditional methods. Genomic Selection (GS) represents a transformative approach, leveraging high-throughput genotyping technologies to overcome the limitations of conventional breeding by enabling more precise genetic selection for desired traits(Heffner et al. 2009).\n\nSeveral factors can influence the prediction accuracy of GS models, including population structure, training population size, and the choice of prediction models (Plavšin et al. 2021). Selecting an appropriate prediction model is a relatively straightforward approach to improve prediction accuracy among these factors. Traditional GS models like Genomic Best Linear Unbiased Prediction (GBLUP) and Ridge Regression (RR) have been foundational, yet they often fail to capture non-linear genetic interactions critical for complex traits like yield (Desta and Ortiz 2014). Emerging models such as Random Forest (RF) and Reproducing Kernel Hilbert Space (RKHS) offer potential improvements by accounting for these complexities . This study aims to explore the predictive capabilities of these advanced models, focusing exclusively on wheat yield (YLD) as a primary trait of interest.\n\nThe data for this analysis stems from a comprehensive dataset encompassing 250 spring wheat lines from diverse genetic backgrounds, evaluated under varying environmental conditions. Six statistical models, namely Ridge Regression (RR), Reproducing Kernel Hilbert Space (RKHS), Genomic Best Linear Unbiased Prediction (GBLUP), Least Absolute Shrinkage and Selection Operator (LASSO), Support Vector Machine (SVM), and Random Forest (RF), were evaluated to identify the optimal model for YLD. Through rigorous analysis and visualization of the genetic predictors of yield, we anticipate fostering a deeper understanding of GS's potential to address pressing food security challenges.\n\n# 2. Data and Code\n\n**Plant Material**\n\nThis study involves 250 spring wheat varieties and elite lines, developed by breeding programs in the Northwestern Pacific region of the United States and the International Maize and Wheat Improvement Center (CIMMYT) in Mexico City, Mexico. The collection includes three market categories of spring wheat cultivated in the Americas: soft white spring, hard white spring, and hard red spring, with over 50% of the lines serving as foundational lines for regional variety development programs.\n\n**Phenotypic Evaluation**\n\nThe wheat panel was evaluated across five distinct environments, labeled E1 to E5 (E1 = 2016, E2 = 2017, E3 = 2021, E4 = 2022, E5 = 2023), at a field trial location in Aberdeen, Idaho (42°56'36\" N and 112°50'22\" W). The trial layout was a randomized complete block design with two replicates. Each genotype was planted in 3.0 m plots consisting of seven rows, with a row spacing of 21 cm. Yield per hectare (kg/ha) was measured in four of these trials (E1, E2, E4, E5).\n\n**Genotyping**\n\nThe population was genotyped using Illumina's 90K iSelect SNPchip. Raw data was provided by the USDA/ARS Cereal Crops Research Unit and was analyzed using Genome Studio v2.0.5(Illumina 2010) for processing its raw data. Polymorphic markers were identified as exhibiting clear, distinct clusters in Genome Studio, with a minimum distance of 0.20 between the polar coordinates of normalized theta intensities. Markers were further filtered based on missing data (\\>10%) and minor allele frequency (\\<5%) using TASSEL v5.2.89 (Bradbury et al. 2007).\n\n**Data Dictionary** \\| Field \\| Description \\| Data Type \\| \\| --------- \\| ------------------------------------------------------------ \\| --------- \\| \\| ENT \\| Unique identifier for each wheat variety, numbered from 52001 to 52250 \\| Integer \\| \\| Source \\| Source of the plant material, including universities (UI, UCD, WSU), CIMMYT, MSU, USDA, and other sources (commercial varieties and international germplasm) \\| String \\| \\| YLD_E1 \\| Yield in kilograms per hectare for environment E1 (2016) \\| Float \\| \\| YLD_E2 \\| Yield in kilograms per hectare for environment E2 (2017) \\| Float \\| \\| YLD_E4 \\| Yield in kilograms per hectare for environment E4 (2022) \\| Float \\| \\| YLD_E5 \\| Yield in kilograms per hectare for environment E5 (2023) \\| Float \\| \\| YLD_BLUPs \\| Best Linear Unbiased Prediction (BLUP) values for yield, calculated from the yields of environments E1, E2, E4, and E5. NA indicates not applicable. \\| Float \\|\n\n# 3. Results\n\n**Phenotypic analysis**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\n\ndata <- read.csv(\"YLD.csv\")\n\ndata[grepl(\"^YLD\", names(data))] <- lapply(data[grepl(\"^YLD\", names(data))], as.numeric)\n  \n\nlong_data <- data %>% \n  pivot_longer(\n    cols = starts_with(\"YLD\"),\n    names_to = \"Year_Rep\",\n    values_to = \"Value\"\n  )\n\n\nlong_data <- long_data %>%\n  mutate(Year = sub(\"-.*\", \"\", Year_Rep))  \n\n# Define a vector of colors including the new one\nmy_colors <- c(\"YLD_BLUPs\" = \"Red\",\"YLD_E3\" =\"#8DD3C7\",\"YLD_E4\" = \"#FDB462\",\"YLD_E5\" =\"#80B1D3\", \"YLD_E1\"=\"yellow\", \"YLD_E2\"=\"#D8BFD8\")\n\n# Density plot with manual colors\np2 <- ggplot(data = long_data, aes(x = Value, fill = Year)) +\n  geom_density(alpha = 0.5) +\n  scale_fill_manual(values = my_colors) +\n  labs(title = \"\", x = \"\", y = \"Density\",fill=\"Environment\") +\n  theme(\n    plot.background = element_rect(fill = \"white\", colour = NA),\n    panel.background = element_rect(fill = \"white\", colour = NA),\n    legend.title = element_text(size = 14),       # Adjust the size of the legend title\n    legend.text = element_text(size = 12),        # Adjust the size of the legend text\n    axis.title.x = element_text(size = 14),       # Adjust the size of the x-axis title\n    axis.title.y = element_text(size = 14),       # Adjust the size of the y-axis title\n    axis.text.x = element_text(size = 12),        # Adjust the size of the x-axis text/labels\n    axis.text.y = element_text(size = 12)         # Adjust the size of the y-axis text/labels\n    )\n\n# Print the plots\nprint(p2)\n```\n\n::: {.cell-output-display}\n![](Index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n| Trait | Env   | Mean     | Range                    | IQR      | CV    | Skewness | Kurtosis |\n|---------|---------|---------|------------|---------|---------|---------|---------|\n| YLD   | E1    | 5687.207 | 3560.188-7753.867±839.68 | 1115.165 | 0.148 | -0.258   | -0.285   |\n|       | E2    | 5528.63  | 4850.76-6181.51±272.1    | 356.24   | 0.05  | -0.18    | -0.22    |\n|       | E4    | 6012.449 | 5512.441-6517.149±178.2  | 216.375  | 0.03  | -0.017   | 0.31     |\n|       | E5    | 6630.67  | 5603.001-7432.273±327.87 | 428.973  | 0.049 | -0.243   | -0.11    |\n|       | BLUPs | 6023.156 | 5340.134-6550.368±223.86 | 290.7    | 0.037 | -0.292   | -0.122   |\n\nYield (YLD) is a critical agronomic trait determining the superiority of wheat varieties. The BLUPs for YLD ranged from 5340.134 to 6550.368 kg/ha. Lowest YLD was observed in E2, with a mean YLD of 6023.156 kg/ha, and highest YLD was observed in E5, with a mean YLD of 6630.67 kg/ha. The distribution YLD demonstrated the most significant variability, with a left-skewed and leptokurtic distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\ndata <- read.csv(\"YLD.csv\")\n\ndata[grepl(\"^YLD\", names(data))] <- lapply(data[grepl(\"^YLD\", names(data))], as.numeric)\n\nALL_cols <- data[, 3:ncol(data)]  \n\n\nfor(i in 1:ncol(data)) {\n  if(is.numeric(data[[i]])) {  \n    data[[i]][is.na(data[[i]])] <- mean(data[[i]], na.rm = TRUE)\n  }\n}\n\n\ncor_matrix <- cor(ALL_cols, use = \"complete.obs\")\n\ncorrplot::corrplot(cor_matrix, method = \"color\", addCoef.col = \"black\", tl.col = \"black\", tl.srt = 30)\n```\n\n::: {.cell-output-display}\n![](Index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe BLUPs values for YLD trait showed high correlations with the trait values across different environments, indicating their effectiveness in integrating phenotypic data from multiple environments for subsequent genetic analysis. Although the correlations between YLD BLUPs and YLD in some environments were slightly lower, they still represented the overall performance of YLD reasonably well\n\n**Population Structure**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\nlibrary(ggplot2)\n\npca_data <- read.csv(\"PCA.csv\")\n\nsource_levels <- c(\"UI\", \"UCD\", \"WSU\", \"CIMMYT\", \"MSU\", \"USDA\", \"Other\")\nsource_counts <- c(111,34,26,25,25,18,10) \n\nsource_levels_with_counts <- paste(source_levels, \"(\", source_counts, \")\", sep = \"\")\n\npca_data$Source <- factor(pca_data$Source, levels = source_levels, labels = source_levels_with_counts)\n\nsource_colors <- c(\"blue\", \"red\", \"gray\", \"purple\", \"orange\", \"black\", \"green\")\ncolors <- setNames(source_colors, source_levels_with_counts) # 创建颜色与来源的映射\n\n\nfig <- plot_ly(pca_data, x = ~PC1, y = ~PC2, z = ~PC3, color = ~Source, colors = colors, type = 'scatter3d', mode = 'markers',\n               marker = list(size = 2)) %>% \n  layout(title = \"\",\n         scene = list(xaxis = list(title = 'Pcomp1:6.3%',titlefont = list(size = 24), tickfont = list(size = 4)),\n                      yaxis = list(title = 'Pcomp2:5.4%',titlefont = list(size = 24), tickfont = list(size = 4)),\n                      zaxis = list(title = 'Pcomp3:4.4%',titlefont = list(size = 24), tickfont = list(size = 4))),\n         legend = list(title = list(text = ''), \n                       traceorder = 'normal', \n                       font = list(size = 10), \n                       bgcolor = 'rgba(255, 255, 255, 0.5)', \n                       bordercolor = 'rgba(0, 0, 0, 0.5)', \n                       borderwidth = 1)) \n                      \nfig\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-7cbcc60752a42b85c0b9\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7cbcc60752a42b85c0b9\">{\"x\":{\"visdat\":{\"10f81f501f8e\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"10f81f501f8e\",\"attrs\":{\"10f81f501f8e\":{\"x\":{},\"y\":{},\"z\":{},\"mode\":\"markers\",\"marker\":{\"size\":2},\"color\":{},\"colors\":[\"blue\",\"red\",\"gray\",\"purple\",\"orange\",\"black\",\"green\"],\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"\",\"scene\":{\"xaxis\":{\"title\":\"Pcomp1:6.3%\",\"titlefont\":{\"size\":24},\"tickfont\":{\"size\":4}},\"yaxis\":{\"title\":\"Pcomp2:5.4%\",\"titlefont\":{\"size\":24},\"tickfont\":{\"size\":4}},\"zaxis\":{\"title\":\"Pcomp3:4.4%\",\"titlefont\":{\"size\":24},\"tickfont\":{\"size\":4}}},\"legend\":{\"title\":{\"text\":\"\"},\"traceorder\":\"normal\",\"font\":{\"size\":10},\"bgcolor\":\"rgba(255, 255, 255, 0.5)\",\"bordercolor\":\"rgba(0, 0, 0, 0.5)\",\"borderwidth\":1},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[-15.44707,-32.215443,-16.725676,-31.754135000000002,-34.114998,-25.437819999999999,30.7364,12.394403000000001,32.696682000000003,28.283481999999999,-34.127659999999999,-26.139030000000002,2.837853,31.744309999999999,-27.874126,-34.234302999999997,-26.141508000000002,-15.015416999999999,6.1577845,-25.507345000000001,-2.3737596999999999,-24.751244,13.514343,-13.059426999999999,-36.655327,-16.555422,-19.228155000000001,-13.506015,-0.080756515000000001,-34.148421999999997,-32.833725000000001,-5.9327015999999997,-2.2751613000000002,-22.188621999999999,-34.932322999999997,-35.684531999999997,3.37927,15.980606999999999,20.893255,4.0348062999999996,-25.038225000000001,-33.173175999999998,-32.397174999999997,7.6078543999999999,3.3968352999999998,3.4977157000000001,22.538252,4.3195750000000004,-26.151678,-30.817905,-33.150309999999998,-4.641438,-4.6552170000000004,-2.7522893000000002,-28.143045000000001,-33.697285000000001,-34.916946000000003,2.6151635999999998,-4.7808989999999998,17.967721999999998,9.9866720000000004,-29.084271999999999,-26.574000999999999,-1.3397729,2.6979853999999999,18.338417,9.7098010000000006,-28.598984000000002,-32.613075000000002,-34.040855000000001,4.0631380000000004,-5.4622444999999997,21.374973000000001,-27.254856,-34.111812999999998,0.77722424000000001,-8.3078059999999994,24.622816,-33.282753,-14.368411999999999,21.511977999999999,18.709949999999999,23.324432000000002,-12.587868,-34.686836,-35.433765000000001,6.3781809999999997,13.9492855,21.044048,9.4665999999999997,-26.758223000000001,-32.525337,-35.709625000000003,4.8581104000000002,13.398648,-8.7945729999999998,-2.5803775999999998,-25.763437,-9.5053990000000006,-33.669322999999999,8.7263099999999998,-4.0912090000000001,25.551071,24.698063000000001,-20.581633,-31.574332999999999,-29.636189000000002,5.6699089999999996,8.8252670000000002,9.3851385000000001,25.169301999999998],\"y\":[5.4325159999999997,-0.9537428,-2.2932174000000001,-2.1842815999999998,-5.3369809999999998,0.24961805000000001,-21.477186,-17.123674000000001,-14.990904,-18.213013,-5.3662175999999997,-3.2536315999999998,-16.564637999999999,-20.743089999999999,-7.0848849999999999,-5.4005264999999998,0.55810004000000002,1.9770966999999999,-18.655273000000001,-2.7940119999999999,-12.128034,-8.2536179999999995,-12.919840000000001,2.1712560000000001,-12.155779000000001,-9.2090169999999993,-1.7411907,-6.9394030000000004,0.81045495999999995,-0.49211597000000001,1.5616874999999999,-12.130292000000001,-12.115602000000001,-2.0775247000000001,-10.592328999999999,-12.010438000000001,15.114459999999999,-8.9007199999999997,-7.8730019999999996,-18.282042000000001,1.960518,-11.532918,-9.4323149999999991,13.980288,-2.5771052999999999,-12.087624,-9.322972,-18.045162000000001,0.27866992000000002,-13.710611,-0.56884170000000001,-11.081284500000001,21.776909,6.5341449999999996,0.31358153,-10.3444805,-2.8767342999999999,-14.320601999999999,-11.671493,-13.677846000000001,-9.9830590000000008,-4.4473060000000002,1.3416958000000001,-12.234050999999999,-12.067278999999999,-10.729069000000001,-14.195751,0.82925450000000001,-4.0377865000000002,-0.09011458,-5.9656152999999996,-6.9769926,-23.267603000000001,-3.0326477999999999,-0.074817010000000003,-0.18793346999999999,-8.0725160000000002,-24.450583999999999,-11.853489,-0.18309998999999999,-17.601590999999999,-12.227496,-19.963304999999998,1.5649233,-9.3671589999999991,-8.1475220000000004,2.6815145,-16.511199999999999,-12.739903999999999,-15.974418999999999,-3.1992775999999998,-9.402704,-12.261108999999999,15.28533,-20.801134000000001,-3.4939034000000002,-0.93775379999999997,-3.7798501999999998,-5.4800972999999997,-8.4873940000000001,18.286814,8.4422920000000001,-16.015989999999999,-12.801297999999999,-6.0436845000000003,-8.2857489999999991,-11.321068,13.075087999999999,-12.584299,7.6024026999999998,-12.515234],\"z\":[-1.1977975000000001,-13.083921999999999,-21.301096000000001,-10.215434,-9.7248509999999992,-1.8971169000000001,-10.959839000000001,-14.816533,-13.420785,-25.165678,-9.6049059999999997,-8.7738370000000003,-7.1311099999999996,-15.780419999999999,-4.791728,-9.687659,-2.1290979999999999,-8.116384,-7.8235000000000001,-24.984978000000002,-6.1927839999999996,-21.183767,-12.979732,-18.723980000000001,-10.252635,-14.435516,-5.6060990000000004,-18.341882999999999,6.7289433000000001,-21.654924000000001,-12.776052,2.7078435000000001,12.412043000000001,-11.565509,-8.2643389999999997,-10.905849,3.56515,4.1922620000000004,-15.850847999999999,-20.095082999999999,-8.8534679999999994,-8.0977080000000008,-10.750939000000001,5.9495490000000002,1.9511746999999999,-8.5760470000000009,-17.524830000000001,-19.929808000000001,-16.799568000000001,-7.1679620000000002,-9.3795979999999997,12.69566,-5.549817,-0.61810743999999995,-6.8314680000000001,-9.6606799999999993,-11.221598,9.0404359999999997,10.890738000000001,-8.3429490000000008,-13.363706000000001,-20.121458000000001,-9.3912759999999995,13.661674,9.2340990000000005,-5.80633,-13.988038,-15.637366999999999,-13.274423000000001,-18.538612000000001,6.4942339999999996,6.2406782999999999,-26.033840000000001,-20.909174,-18.537545999999999,12.300948999999999,8.1885250000000003,-23.720053,-10.142035999999999,-6.7789792999999996,-5.8446373999999999,-4.8078390000000004,-24.608460999999998,-5.0871909999999998,-4.2634340000000002,-8.2318090000000002,-0.67402863999999996,-20.619629,-7.7599983000000003,-17.191117999999999,-10.760811,-3.7536402,-11.023362000000001,5.0917306,-16.810400000000001,8.0431740000000005,5.1431893999999998,-7.0369020000000004,-3.3642395,-8.5952120000000001,0.46991317999999999,-3.6828197999999999,-10.50539,-7.8678675,-4.7066480000000004,-2.0850293999999998,-9.3858169999999994,8.129607,3.121146,-16.941382999999998,-8.0725510000000007],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(0,0,255,1)\",\"size\":2,\"line\":{\"color\":\"rgba(0,0,255,1)\"}},\"type\":\"scatter3d\",\"name\":\"UI(111)\",\"textfont\":{\"color\":\"rgba(0,0,255,1)\"},\"error_y\":{\"color\":\"rgba(0,0,255,1)\"},\"error_x\":{\"color\":\"rgba(0,0,255,1)\"},\"line\":{\"color\":\"rgba(0,0,255,1)\"},\"frame\":null},{\"x\":[10.331939,10.350484,9.9852980000000002,10.26037,23.321103999999998,-2.8497617000000002,-7.7105516999999999,0.45173219999999997,11.636003000000001,15.486513,2.1843306999999998,12.419547,11.741676999999999,8.6108499999999992,2.1994486000000002,9.3472089999999994,5.0745639999999996,6.6936817,1.8293661000000001,-3.454688,-7.6372156000000002,5.4884019999999998,15.571799,9.2991489999999999,2.4783236999999998,-7.6991443999999998,10.533604,11.392241,7.9581784999999998,6.7672160000000003,19.834478000000001,3.5829034000000002,16.416284999999998,17.663799999999998],\"y\":[1.7784711,1.7674936999999999,2.1048290000000001,1.6886399000000001,-4.0777840000000003,14.355981,22.786284999999999,-6.0081015000000004,-10.148372,-11.809514999999999,3.4307196000000002,-7.2339387000000004,-13.161492000000001,-3.8598330000000001,1.4187669000000001,-0.45076667999999998,-11.091713,-13.904216999999999,0.90905314999999998,6.5677047000000002,11.621297,-3.3049192000000001,-7.1848679999999998,-11.09825,-6.5387244000000004,22.772936000000001,-12.592233999999999,-5.0510529999999996,-4.7882680000000004,-11.398645999999999,-3.8075022999999999,1.2230216,8.5927105000000008,1.6075172],\"z\":[24.862335000000002,24.888342000000002,25.30855,24.472479,7.7937079999999996,7.4946089999999996,-2.8421736000000002,7.6137794999999997,15.275496499999999,23.850489,5.3668393999999999,15.69361,17.790863000000002,2.9235191,9.1700809999999997,18.537849999999999,-4.6311045000000002,-3.453789,12.832621,17.989550000000001,15.075472,19.502362999999999,9.6184224999999994,5.3304935000000002,4.2859863999999996,-2.8303337000000002,17.600425999999999,6.8906926999999998,10.397311,5.8900747000000004,10.460248999999999,10.232813,5.3755280000000001,5.1617850000000001],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(255,0,0,1)\",\"size\":2,\"line\":{\"color\":\"rgba(255,0,0,1)\"}},\"type\":\"scatter3d\",\"name\":\"UCD(34)\",\"textfont\":{\"color\":\"rgba(255,0,0,1)\"},\"error_y\":{\"color\":\"rgba(255,0,0,1)\"},\"error_x\":{\"color\":\"rgba(255,0,0,1)\"},\"line\":{\"color\":\"rgba(255,0,0,1)\"},\"frame\":null},{\"x\":[15.445591,21.627783000000001,29.526523999999998,32.872399999999999,27.013877999999998,27.143129999999999,27.263338000000001,33.538531999999996,24.793130000000001,13.793333000000001,23.00347,25.196321000000001,26.753692999999998,26.285796999999999,1.1625273,25.080645000000001,32.611150000000002,25.599209999999999,26.271559,31.847624,29.125637000000001,6.8010539999999997,3.2883718000000002,2.1246442999999999,-9.9553720000000006,-19.167449999999999],\"y\":[30.235800000000001,16.441655999999998,-26.221402999999999,-22.423449000000002,-11.249644,14.563737,-6.0535819999999996,-1.8252103,-20.684367999999999,-8.1396599999999992,-24.725708000000001,-17.812957999999998,-4.2090063000000004,-20.690424,-19.286701000000001,14.604225,-15.388866,16.037745999999999,13.313015999999999,-22.471771,-15.475742,-8.8630420000000001,-18.426226,-12.879953,8.8997250000000001,-2.4257561999999999],\"z\":[-17.686216000000002,-13.078222,-21.244441999999999,-22.065659,-10.5785055,-4.2840809999999996,-9.4842549999999992,-13.858162999999999,-12.110533999999999,1.3436513000000001,-13.786782000000001,-5.1296425000000001,-9.0717960000000009,-8.0590449999999993,-12.209638,-4.3133736000000003,-16.940435000000001,-3.9105713,-3.7007564999999998,-12.956204,-17.521827999999999,7.4325099999999997,-12.681227,1.7299523000000001,-13.014701000000001,-5.2628507999999998],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(190,190,190,1)\",\"size\":2,\"line\":{\"color\":\"rgba(190,190,190,1)\"}},\"type\":\"scatter3d\",\"name\":\"WSU(26)\",\"textfont\":{\"color\":\"rgba(190,190,190,1)\"},\"error_y\":{\"color\":\"rgba(190,190,190,1)\"},\"error_x\":{\"color\":\"rgba(190,190,190,1)\"},\"line\":{\"color\":\"rgba(190,190,190,1)\"},\"frame\":null},{\"x\":[3.4693797000000002,2.7668366,2.7281816000000001,6.5784326000000002,-5.3880600000000003,2.6524071999999999,3.0325405999999999,-1.8679768000000001,-4.3175496999999998,-1.4257808999999999,3.9288826000000001,-6.0802420000000001,14.226685,4.5558269999999998,-6.8894479999999998,-5.9963220000000002,-5.4991726999999999,0.91549873000000004,-1.0155240000000001,4.8036440000000002,-4.0041450000000003,-2.6468272000000002,-5.1049179999999996,-2.8608408000000001,1.0689995000000001],\"y\":[12.056355999999999,1.3499368,10.476063,-3.185622,4.9550380000000001,10.986326,-1.3894359999999999,1.615791,7.1805944000000004,7.8987119999999997,2.5683221999999999,0.41214933999999998,-4.5361485000000004,5.6590119999999997,10.067966999999999,5.9413799999999997,5.555053,1.5450457,-1.1663504,7.8950189999999996,1.4675418,0.054976758000000001,-0.15199952,14.592993,0.50347410000000004],\"z\":[13.048162,36.873289999999997,27.043780000000002,27.638445000000001,22.32789,19.314164999999999,10.413245999999999,30.302948000000001,28.933947,5.684088,22.775503,16.843958000000001,12.754771,11.931811,25.088401999999999,19.434498000000001,28.313654,11.595468500000001,25.809564999999999,18.231596,31.212430999999999,12.747389,17.194794000000002,23.972273000000001,17.637953],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(160,32,240,1)\",\"size\":2,\"line\":{\"color\":\"rgba(160,32,240,1)\"}},\"type\":\"scatter3d\",\"name\":\"CIMMYT(25)\",\"textfont\":{\"color\":\"rgba(160,32,240,1)\"},\"error_y\":{\"color\":\"rgba(160,32,240,1)\"},\"error_x\":{\"color\":\"rgba(160,32,240,1)\"},\"line\":{\"color\":\"rgba(160,32,240,1)\"},\"frame\":null},{\"x\":[14.9524765,8.7085699999999999,10.531169,2.5114887000000001,15.483193999999999,14.633379,11.7476425,4.9501552999999996,7.0606746999999999,8.5779969999999999,2.0666549999999999,18.489698000000001,16.831869999999999,-2.187046,13.936149,2.8683323999999999,24.516694999999999,4.9901704999999996,2.9720092,5.0860799999999999,12.759233,25.265785000000001,25.576712000000001,5.6842421999999999,16.155424],\"y\":[21.089008,21.405348,38.41648,68.119020000000006,42.675423000000002,27.351520000000001,46.463912999999998,67.904979999999995,41.662135999999997,49.778216999999998,67.722176000000005,32.972569999999997,-14.463366000000001,16.720654,23.563808000000002,67.892169999999993,-7.4330005999999997,66.508223999999998,58.441417999999999,36.051814999999998,39.783596000000003,7.5386214000000002,-19.993559000000001,26.400971999999999,16.165346],\"z\":[-8.4393630000000002,-13.020458,-11.799671,-15.607934999999999,-15.050223000000001,-10.397368999999999,-18.498045000000001,-11.516997999999999,-14.907904,-16.382273000000001,-15.491231000000001,-12.642913999999999,-7.4299911999999999,-9.8192179999999993,2.9294585999999998,-15.428326999999999,-18.769846000000001,-11.920992999999999,-16.455976,-13.656017,-16.332684,-25.257930000000002,-20.245052000000001,-7.4550346999999997,-9.9215710000000001],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(255,165,0,1)\",\"size\":2,\"line\":{\"color\":\"rgba(255,165,0,1)\"}},\"type\":\"scatter3d\",\"name\":\"MSU(25)\",\"textfont\":{\"color\":\"rgba(255,165,0,1)\"},\"error_y\":{\"color\":\"rgba(255,165,0,1)\"},\"error_x\":{\"color\":\"rgba(255,165,0,1)\"},\"line\":{\"color\":\"rgba(255,165,0,1)\"},\"frame\":null},{\"x\":[-6.3194184,-3.8800694999999998,-2.2793313999999998,6.6069335999999996,-2.2487154,-5.8572664000000003,4.1128030000000004,1.5415574000000001,0.58936999999999995,0.78647420000000001,1.9260746,0.81191559999999996,-6.0015507000000001,-6.4647436000000003,-2.6004200000000002,-5.6300793000000002,-5.1696115000000002,-5.3408246000000004],\"y\":[0.57646114000000004,-1.8622477,1.1120243000000001,-4.0835147000000003,1.6553922000000001,0.83188260000000003,-0.55163443000000001,-1.6444240999999999,-2.7937584000000002,-8.4223169999999996,-7.5397249999999998,-0.39789799999999997,2.5595899000000002,1.023379,-3.0600922000000002,-5.9853997000000003,-4.9478374000000001,-4.8451667],\"z\":[24.913435,25.037645000000001,22.349205000000001,24.784859999999998,21.875586999999999,24.545615999999999,24.182552000000001,17.905532999999998,16.842466000000002,16.242228000000001,18.913592999999999,22.812211999999999,26.193314000000001,24.623163000000002,23.449649999999998,21.055693000000002,21.600753999999998,21.462729],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(0,0,0,1)\",\"size\":2,\"line\":{\"color\":\"rgba(0,0,0,1)\"}},\"type\":\"scatter3d\",\"name\":\"USDA(18)\",\"textfont\":{\"color\":\"rgba(0,0,0,1)\"},\"error_y\":{\"color\":\"rgba(0,0,0,1)\"},\"error_x\":{\"color\":\"rgba(0,0,0,1)\"},\"line\":{\"color\":\"rgba(0,0,0,1)\"},\"frame\":null},{\"x\":[-0.67201655999999999,14.712088,-10.867772,-5.5484669999999996,-2.4553988000000002,-5.92584,-10.523057,-10.049200000000001,-2.3688145,-5.9304842999999998],\"y\":[-11.863670000000001,30.649977,3.0684136999999998,1.9744809999999999,0.1016986,1.7638309999999999,7.420274,7.9214362999999999,-4.1139846000000002,-12.124072],\"z\":[3.1974893,-3.6412756000000002,20.335906999999999,22.053621,25.094866,21.922522000000001,29.362362000000001,29.548456000000002,7.9406119999999998,2.7131764999999999],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(0,255,0,1)\",\"size\":2,\"line\":{\"color\":\"rgba(0,255,0,1)\"}},\"type\":\"scatter3d\",\"name\":\"Other(10)\",\"textfont\":{\"color\":\"rgba(0,255,0,1)\"},\"error_y\":{\"color\":\"rgba(0,255,0,1)\"},\"error_x\":{\"color\":\"rgba(0,255,0,1)\"},\"line\":{\"color\":\"rgba(0,255,0,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nPrincipal component analysis (PCA) based on the genotypic data revealed a clear population structure among the 249 spring wheat lines (Fig. 5). The first three principal components (PCs) explained 6.3%, 5.4%, and 4.4% of the total genetic variance, respectively. The 3D PCA plot showed distinct clustering of lines according to their sources. The number of lines within each cluster ranged from 10 (Other) to 111 (UI). The largest cluster consisted of 111 lines from the University of Idaho (UI), followed by 34 lines from UC Davis (UCD) and 26 lines from Washington State University (WSU).\n\n| Df  | Sum Sq      | Mean Sq     | F value     | Pr(\\>F)  | R^2^  |\n|-----|-------------|-------------|-------------|----------|-------|\n| 6   | 1383462.467 | 230577.0778 | 5.068379905 | 6.41E-05 | 11.1% |\n| 242 | 11009366.68 | 45493.25073 | NA          |          |       |\n\nAnalysis of variance (ANOVA) revealed that the population structure had significant effects on all five traits analyzed (P \\< 0.001) .\n\n**Comparison of Genomic Prediction Models**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(reshape2)\nlibrary(ggplot2)\ntrait=c(\"YLD\")\n\ndata <- read.csv(paste0(\"compare.YLD.16Modify.17.22.23.BLUP.csv\"), header = TRUE)\n  \n  \ndata_melted <- melt(data)\n  \np<-ggplot(data_melted, aes(x = variable, y = value)) +\n  geom_boxplot() +\n  theme(axis.text.x = element_text(angle = 0, size = 20), \n        axis.text.y = element_text(size = 20), \n        axis.title.x = element_text(size = 20), \n        axis.title.y = element_text(size = 20)) + \n  labs(x = \"Model\", y = paste0(\"Prediction Accuracy for \",trait), title = \"\")\nprint(p)\n```\n\n::: {.cell-output-display}\n![](Index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nSix statistical models, including GBLUP, RKHS, RF, RR LASSO, and SVM, were evaluated using a five-fold cross-validation scheme with 50 replications to identify the optimal model for predicting HD, PHT, TKW, tSNS, and YLD based on the BLUPs of phenotypic data. The SVM model consistently showed the lowest prediction accuracies，while RKHS and RF demonstrated similar and superior performance compared to the other models, including the widely used GBLUP and RR\n\nConsidering the comparable performance of RKHS and RF, we selected RF as the optimal model for genomic prediction in this study. Second, Charmet et al.(2020a) previously evaluated the computational efficiency of various prediction methods using a set of 47,839 markers and 100 independent 10-fold cross-validations. They found that RF (382 minutes) was considerably less computationally intensive than RKHS (637 minutes), making RF a more practical choice for large-scale genomic prediction applications.\n\n**Testing Prediction across Environment**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"merged_GP502-RF-YLD.16Modify.17.22.23_filtered.csv\")\n\nlibrary(tidyr)\ndata_long <- gather(data, key = \"Measurement\", value = \"Value\", BLUPs_RF:E5_RF)\n\nlibrary(ggplot2)\n\nmy_colors <- c(\"BLUPs_RF\" = \"Red\", \"E3_RF\" =\"#8DD3C7\", \"E4_RF\" = \"#FDB462\", \"E5_RF\" =\"#80B1D3\", \"E1_RF\"=\"yellow\", \"E2_RF\"=\"#D8BFD8\")\n\nggplot(data_long, aes(x = ...2\n, y = Value, fill = Measurement)) +\n  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5) +\n  scale_fill_manual(values = my_colors) +\n  labs(title = \"\",\n       x = \"Training Environment\", y = \"Prediction Accuracy for YLD\", fill=\"\") +\n  theme_minimal() +\n  theme(plot.background = element_rect(fill = \"white\", colour = NA),   \n        panel.background = element_rect(fill = \"white\", colour = NA), \n        legend.title = element_text(size = 14),       \n        legend.text = element_text(size = 12),        \n        axis.title.x = element_text(size = 12),       \n        axis.title.y = element_text(size = 12),       \n        axis.text.x = element_text(size = 8, angle = 0), \n        axis.text.y = element_text(size = 10),        \n        #legend.position = \"null\",                    \n        plot.title = element_text(hjust = 0))         \n```\n\n::: {.cell-output-display}\n![](Index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n| TRAITS | TRAINING ENVIRONMENTS | PREDICTION ENVIRONMENTS | PREDICTION ACCURACIES A |\n|:---------------|:-----------------|:-------------------|:-------------------|\n| YLD    | BLUPs                 | BLUPs                   | 0.424                   |\n|        |                       | E1                      | 0.369                   |\n|        |                       | E2                      | 0.325                   |\n|        |                       | E4                      | 0.189                   |\n|        |                       | E5                      | 0.240                   |\n| YLD    | E1                    | BLUPs                   | 0.288                   |\n|        |                       | E1                      | 0.565                   |\n|        |                       | E2                      | 0.277                   |\n|        |                       | E4                      | 0.109                   |\n|        |                       | E5                      | -0.052                  |\n| YLD    | E2                    | BLUPs                   | 0.319                   |\n|        |                       | E1                      | 0.343                   |\n|        |                       | E2                      | 0.360                   |\n|        |                       | E4                      | 0.140                   |\n|        |                       | E5                      | 0.041                   |\n| YLD    | E4                    | BLUPs                   | 0.161                   |\n|        |                       | E1                      | 0.242                   |\n|        |                       | E2                      | 0.129                   |\n|        |                       | E4                      | 0.078                   |\n|        |                       | E5                      | 0.058                   |\n| YLD    | E5                    | BLUPs                   | 0.259                   |\n|        |                       | E1                      | 0.024                   |\n|        |                       | E2                      | 0.053                   |\n|        |                       | E4                      | 0.127                   |\n|        |                       | E5                      | 0.395                   |\n\nIn this study, we investigated the prediction accuracy of yield-related traits (HD, PHT, TKW, and tSNS) and yield (YLD) across different environments using the optimal model determined in the previous section (Random Forest with 80% of the population as the training set). Prediction accuracies are reported as the median value.\n\nSingle-environment models were trained by training and predicting within the same environment. For YLD, the prediction accuracies were highest for environment E1 and BLUPs, respectively. BLUPs outperformed 80% of the evaluation environments.When models were trained in one environment and used to predict in different environments, substantial variation in prediction accuracy was observed across environment combinations for all traits. For YLD, prediction accuracy ranged from -0.052 to 0.565 for different training-testing environment combinations, and from 0.189 to 0.424 when using BLUPs to train the model.Overall, BLUPs were best suited for training models to predict values in unknown environments, whether using single-environment models or cross-environment models.\n\n# 4. Conclusion\n\nWheat is a staple food crop worldwide, with its yield improvement being crucial for food security. Genomic selection accelerates the breeding process and enhances genetic gains in wheat. This study demonstrated the potential of genomic prediction models, particularly Random Forest, in predicting yield. And BLUPs data is the best data set for training and prediction.\n\n# 5. Reference\n\nBradbury PJ, Zhang Z, Kroon DE, Casstevens TM, Ramdoss Y, and Buckler ES. TASSEL: software for association mapping of complex traits in diverse samples. Bioinformatics. 2007:23(19):2633--2635. https://doi.org/10.1093/bioinformatics/btm308 Charmet G, Tran L-G, Auzanneau J, Rincent R, and Bouchet S. BWGS: AR package for genomic selection and its application to a wheat breeding programme. PloS one. 2020:15(4):e0222733. https://doi.org/10.1371/journal.pone.0222733 Desta ZA and Ortiz R. Genomic selection: genome-wide prediction in plant improvement. Trends in plant science. 2014:19(9):592--601. https://doi.org/10.1016/j.tplants.2014.05.006 Heffner EL, Sorrells ME, and Jannink J-L. Genomic Selection for Crop Improvement. Crop Science. 2009:49(1):1--12. https://doi.org/10.2135/cropsci2008.08.0512 Illumina. Introduction to GenomeStudio Software. 2010. Plavšin I, Gunjača J, Šatović Z, Šarčević H, Ivić M, Dvojković K, and Novoselović D. An overview of key factors affecting genomic selection for wheat quality traits. Plants. 2021:10(4):745. https://doi.org/10.3390/plants10040745 Zhang T, He Y, DePauw R, Jin Z, Garvin D, Yue X, Anderson W, Li T, Dong X, Zhang T, et al. Climate change may outpace current wheat breeding yield improvements in North America. Nature Communications. 2022:13(1):5591. https://doi.org/10.1038/s41467-022-33265-1\n",
    "supporting": [
      "Index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}