# 载入需要的包
library(reshape2)
library(ggplot2)
traits=c("HD","PHT","TKW","tSNS","YLD")
save_dir<- "E:\\06-实验\\00-6-GP502-GWAS\\06-第一篇文章数据\\03-Population Division(RF)\\Data and Code used for analysis\\"

for (trait in traits){
# 读取数据
  data <- read.csv(paste0("E:\\06-实验\\00-6-GP502-GWAS\\06-第一篇文章数据\\03-Population Division(RF)\\Data and Code used for analysis\\",trait,".csv"), header = TRUE)
  
  # 将数据从宽格式转换为长格式
  data_melted <- melt(data)
  
  # 移除variable列值中的开头的'X'
  data_melted$variable <- sub('^X', '', data_melted$variable)

  # 绘制Boxplot
 # 绘制Boxplot
  p<-ggplot(data_melted, aes(x = variable, y = value)) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 0, size = 30), # 修改X轴字体大小
        axis.text.y = element_text(size = 30), # 修改Y轴字体大小
        axis.title.x = element_text(size = 30), # 修改X轴标题字体大小
        axis.title.y = element_text(size = 30)) + # 修改Y轴标题字体大小
   labs(x = "Percentage of lines in training set", y = paste0("Prediction Accuracy for ",trait), title = "")
  print(p)

  # 构建文件名
  filename <- paste0(save_dir, "Boxplot_", trait, ".png")
  
  # 保存图形
  ggsave(filename, plot = p, width = 12, height = 8)
}