library(ggplot2)
library(readr) 
library(tidyr)
library(dplyr)

# 定义变量名列表
variables <- c("GBLUP", "RKHS", "RF", "RR")

# 设置文件夹路径  
folder_path <- "E:/06-实验/00-6-GP502-GWAS/00-Temp"

# 遍历变量名
for (variable in variables) {
  
  # 构建针对当前变量的文件名
  file_name <- paste0(folder_path, "/GP502-GS-prediction-clean-", variable, ".csv")
  
  # 读取数据
  data <- read.csv(file_name)
  
  # 选取Mean数据
  mean_data <- data[data$Source == "Mean",]
  
  # 转换数据为长格式
  mean_long <- pivot_longer(mean_data, cols = -c(Source1, Source), names_to = "Trait", values_to = "Mean")
  
  # 绘制条形图并在条形上方添加Mean值标签
  p <- ggplot(mean_long, aes(x = Trait, y = Mean, fill = Source1)) + 
    geom_bar(stat = "identity", position = position_dodge()) +
    geom_text(aes(label = round(Mean, 3)), vjust = -0.5, 
              position = position_dodge(width = 0.9), size = 3) +
    theme_minimal() +
    labs(x ="Training Environment" , y =  "Prediction Accuracy for YLD", title = "", fill = NULL) +
    theme(legend.position = "right")
  
  # 打印图形
  print(p)
  
  # 保存图形到文件,包括变量名  
  plot_file_name <- paste0(folder_path, "/GP502-GS-prediction-plot-", variable, ".jpg")
  ggsave(plot_file_name, p, width = 12, height = 8)
  
}