
# 读取CSV文件

data <- read.csv("merged_GP502-RF-YLD.16Modify.17.22.23_filtered.csv")

# 将数据转换为长格式
library(tidyr)
data_long <- gather(data, key = "Measurement", value = "Value", BLUPs_RF:E5_RF)

# 创建箱线图
library(ggplot2)

my_colors <- c("BLUPs_RF" = "Red", "E3_RF" ="#8DD3C7", "E4_RF" = "#FDB462", "E5_RF" ="#80B1D3", "E1_RF"="yellow", "E2_RF"="#D8BFD8")

ggplot(data_long, aes(x = ...2
, y = Value, fill = Measurement)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5) +
  scale_fill_manual(values = my_colors) +
  labs(title = "",
       x = "Training Environment", y = "Prediction Accuracy for YLD.16Modify.17.22.23(RF)", fill="") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white", colour = NA),   # 设置绘图背景
        panel.background = element_rect(fill = "white", colour = NA),  # 设置面板背景
        legend.title = element_text(size = 24),       # 调整图例标题的大小
        legend.text = element_text(size = 22),        # 调整图例文本的大小
        axis.title.x = element_text(size = 22),       # 调整x轴标题的大小
        axis.title.y = element_text(size = 22),       # 调整y轴标题的大小
        axis.text.x = element_text(size = 18, angle = 0), # 合并设置x轴文本的大小和角度
        axis.text.y = element_text(size = 20),        # 调整y轴文本/标签的大小
        #legend.position = "null",                    # 设置图例位置
        plot.title = element_text(hjust = 0))         # 设置标题的水平对齐方式
        
        

# 读取CSV文件
setwd("E:\\06-实验\\00-6-GP502-GWAS\\00-Temp\\YLD.16Modify.17.22.23")
data <- read.csv("merged_GP502-RKHS-YLD.16Modify.17.22.23_filtered.csv")

# 将数据转换为长格式
library(tidyr)
data_long <- gather(data, key = "Measurement", value = "Value", BLUPs_RKHS:E5_RKHS)

# 创建箱线图
library(ggplot2)

my_colors <- c("BLUPs_RKHS" = "Red", "E3_RKHS" ="#8DD3C7", "E4_RKHS" = "#FDB462", "E5_RKHS" ="#80B1D3", "E1_RKHS"="yellow", "E2_RKHS"="#D8BFD8")

ggplot(data_long, aes(x = ...2
, y = Value, fill = Measurement)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5) +
  scale_fill_manual(values = my_colors) +
  labs(title = "",
       x = "Training Environment", y = "Prediction Accuracy for YLD.16Modify.17.22.23(RKHS)", fill="") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white", colour = NA),   # 设置绘图背景
        panel.background = element_rect(fill = "white", colour = NA),  # 设置面板背景
        legend.title = element_text(size = 24),       # 调整图例标题的大小
        legend.text = element_text(size = 22),        # 调整图例文本的大小
        axis.title.x = element_text(size = 22),       # 调整x轴标题的大小
        axis.title.y = element_text(size = 22),       # 调整y轴标题的大小
        axis.text.x = element_text(size = 18, angle = 0), # 合并设置x轴文本的大小和角度
        axis.text.y = element_text(size = 20),        # 调整y轴文本/标签的大小
        legend.position = "null",                    # 设置图例位置
        plot.title = element_text(hjust = 0))         # 设置标题的水平对齐方式
        