library(dplyr)
library(tidyr)
library(ggplot2)




######
# 读取数据
data <- read.csv("YLD.csv")

######

# 将所有以YLD开头的列转换为double类型
data[grepl("^YLD", names(data))] <- lapply(data[grepl("^YLD", names(data))], as.numeric)
  

# 将数据转换为长格式
long_data <- data %>% 
  pivot_longer(
    cols = starts_with("YLD"),
    names_to = "Year_Rep",
    values_to = "Value"
  )

  
######
write.csv(long_data, file = "GP502-YLD-adjusted-long_data.csv", row.names = FALSE)
######


# 查看转换后的数据
head(long_data)

# 假设您已经将数据转换为长格式，并存储在long_data中
long_data <- long_data %>%
  mutate(Year = sub("-.*", "", Year_Rep))  # 提取年份

# Define a vector of colors including the new one
my_colors <- c("YLD_BLUPs" = "Red","YLD_E3" ="#8DD3C7","YLD_E4" = "#FDB462","YLD_E5" ="#80B1D3", "YLD_E1"="yellow", "YLD_E2"="#D8BFD8")

# Density plot with manual colors
p2 <- ggplot(data = long_data, aes(x = Value, fill = Year)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = my_colors) +
  labs(title = "", x = "", y = "Density",fill="Environment") +
  theme(
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    legend.title = element_text(size = 24),       # Adjust the size of the legend title
    legend.text = element_text(size = 22),        # Adjust the size of the legend text
    axis.title.x = element_text(size = 24),       # Adjust the size of the x-axis title
    axis.title.y = element_text(size = 24),       # Adjust the size of the y-axis title
    axis.text.x = element_text(size = 22),        # Adjust the size of the x-axis text/labels
    axis.text.y = element_text(size = 22)         # Adjust the size of the y-axis text/labels
    )

# Print the plots
print(p1)
print(p2)

# Optionally, save the plots to a file
ggsave("YLD_boxplot_custom_colors.png", plot = p1, width = 10, height = 8, background = "white")
ggsave("YLD_density_custom_colors.png", plot = p2, width = 10, height = 8, background = "white")

library(readxl)

## 相关性分析
## 不同年份相关性分析
# 读取数据
data <- read.csv("YLD.csv")

# 将所有以YLD开头的列转换为double类型
data[grepl("^YLD", names(data))] <- lapply(data[grepl("^YLD", names(data))], as.numeric)

# 选择YLD的列 #要更改
ALL_cols <- data[, 3:ncol(data)]  # 假设YLD数据从第4列开始

# 处理缺失值（如果有）
for(i in 1:ncol(data)) {
  if(is.numeric(data[[i]])) {  # 确保只对数值型列操作
    data[[i]][is.na(data[[i]])] <- mean(data[[i]], na.rm = TRUE)
  }
}


# 计算相关性矩阵
cor_matrix <- cor(ALL_cols, use = "complete.obs")

# 可视化相关性矩阵
corrplot::corrplot(cor_matrix, method = "color", addCoef.col = "black", tl.col = "black", tl.srt = 45)



